### ISSUE TITLE
Biography Interface

### ISSUE THREAD

**Issue by johannesliem** [InTaVia/api-client#23]
Add biography interface to model

```
interface Biography {
   id: Entity['id'];
   text: string;
}
```

**Comment by stefanprobst** [comment]
what endpoint returns this?

**Comment by johannesliem** [comment]
There will be an endpoint that returns biographical texts (e.g. the biography source texts of APIS). Also the xlsx template will provide the option to import biographical text, indexed by entity id.

**Comment by johannesliem** [comment]
relates to https://github.com/InTaVia/InTaVia-Backend/issues/77
The plan for now, is that this endpoint queries the existing APIS API for biography texts; Alternatively we could directly access the api in the frontend.

**Comment by stefanprobst** [comment]
ok, should this be added as a field to `Person` then?

i.e.

```diff
export interface Biography {
- id: Entity['id'];
+ id: string;
  text: string;
}

export interface Person extends EntityBase {
  kind: "person";
  gender?: Gender;
  occupations?: Array<Pick<VocabularyEntry, "id" | "label">>;
+ biographies?: Array<Biography['id']>
}
```
