### ISSUE TITLE
Activate Media Property in EntityBase

### ISSUE THREAD

**Issue by johannesliem** [InTaVia/api-client#24]
Uncomment media property in EntityBase (model) to be used for local import

**Comment by stefanprobst** [comment]
does this shape still make sense: https://github.com/InTaVia/api-client/blob/main/src/models.ts#L40-L46

**Comment by stefanprobst** [comment]
maybe with attribution optional

also, `MediaKind` should probably be some kind of enum or vocabulary

**Comment by johannesliem** [comment]
The shape still makes sense from my point of view.

I Agree
- MediaKind` should be a vocabulary 
- Attribution can be optional

For now the backend won't provide any MediaResources, but it will be used by the local import (Dürer) for the workshops.

**Comment by stefanprobst** [comment]
> MediaKind` should be a vocabulary

what do we need for local data import? `image | video | document`?

**Comment by johannesliem** [comment]
I believe those types are good for now, cannot think of any other.

Maybe it does make sense if we add a `title` or `label` property to the MediaResource interface. While often an image will be linked to a cho object (which already has a title info), in other cases when linked to other entity types a title might be useful (in addition to the description).
