### ISSUE TITLE
Proposal: Media Resources For Events

### ISSUE THREAD

**Issue by johannesliem** [InTaVia/api-client#36]
Especially important for local data and storytelling, to relate e.g. images to a certain event.
E.g., the state of the Hofburg at a given point in time (which is modelled as an event) represented by an image, which then can be automatically used in storytelling (e.g. in popups or in content sections)

https://github.com/InTaVia/api-client/blob/0cdcb7d5511367c2cc3ea2b1ed8b22963d586e06/src/models.ts#L101-L110

extend above by media prop:

```
export interface Event {
	id: string;
	label: InternationalizedLabel;
	// description?: string;
	kind: EventKind["id"];
	// source?: Source;
	startDate?: IsoDateString;
	endDate?: IsoDateString;
        media?: Array<MediaResource["id"]>;
	relations: Array<EventEntityRelation>;
}	
```

**Comment by stefanprobst** [comment]
done
